name: soul
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  convex_bottom_bar: ^3.2.0
  go_router: ^6.0.0
  rive: ^0.13.14
  http: ^1.2.2
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  path_provider: ^2.0.11
  intl: ^0.17.0
  uuid: ^3.0.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  gif: 2.3.0
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true

  assets:
    - assets/mood_2.jpg
    - assets/mood_1.jpg
    - assets/mood_3.jpg
    - assets/question.webp
    - assets/reminder.webp
    - assets/signup.webp
    - assets/google.png
    - assets/login.webp
    - assets/bg.png
    - assets/bg.jpg
    - assets/bggrey.jpg
    - assets/bgblue.jpg
    - assets/bgblack.jpg
    - assets/bgtorq.jpg
    - assets/soulbg.jpg
    - assets/bg2.jpeg
    - assets/bg3.jpeg
    - assets/sound.png
    - assets/profile.png
    - assets/mic.gif
    - assets/bot.png
    - assets/shapes.riv
    - assets/robot.riv
    - assets/robocat.riv
    - assets/icons.riv

  fonts:
    - family: MontserratAlternates
      fonts:
        - asset: fonts/MontserratAlternates-Regular.ttf